<?php

namespace Tests\Unit\Controllers;

use App\Http\Controllers\Controller;
use Tests\TestCase;

/**
 * Test stub for base Controller class.
 *
 * This is the base abstract controller that all API controllers extend.
 * Generated by AI-07 TDD Test Stub workflow.
 */
class ControllerTest extends TestCase
{
    /**
     * Test that the base controller is abstract and cannot be directly instantiated.
     * Uses reflection to verify the abstract nature.
     */
    public function test_controller_is_abstract(): void
    {
        $reflection = new \ReflectionClass(Controller::class);
        $this->assertTrue($reflection->isAbstract());
    }

    /**
     * Test that the base controller uses AuthorizesRequests trait.
     */
    public function test_controller_uses_authorizes_requests_trait(): void
    {
        $traits = class_uses(Controller::class);
        $this->assertContains('Illuminate\Foundation\Auth\Access\AuthorizesRequests', $traits);
    }

    /**
     * Test concrete subclass can be instantiated and has access to trait methods.
     * Concrete implementation of the abstract Controller for testing.
     */
    public function test_concrete_subclass_can_be_instantiated(): void
    {
        $dummy = new class extends Controller {};
        $this->assertInstanceOf(Controller::class, $dummy);
    }

    /**
     * Test that subclasses can use the ApiResponse trait.
     */
    public function test_subclasses_have_access_to_api_response_trait(): void
    {
        // TODO: Implement test
        // Expected: All controllers extending Controller have access to success(), error(), created(), deleted()
        $this->markTestIncomplete();
    }

    /**
     * Test that controllers extending Controller have expected base functionality.
     */
    public function test_base_controller_provides_shared_functionality(): void
    {
        // TODO: Implement test
        // Expected: Controllers inherit any shared methods from the base Controller
        $this->markTestIncomplete();
    }
}

/**
 * Concrete implementation of Controller for testing purposes.
 */
class ConcreteDummyController extends Controller
{
    use \App\Http\Traits\ApiResponse;

    public function dummyAction()
    {
        return $this->success(['test' => 'ok']);
    }
}
